### ISSUE TITLE
Fix  [edit section] links

### ISSUE THREAD

**Issue by hacklschorsch** [Rican7/MediaWiki-MarkdownExtraParser#2]
The [known conflicts list](http://www.mediawiki.org/wiki/Extension:MarkdownExtraParser#Conflicts) says

> If you want an [edit section] link, you have to use MediaWiki headings (== Heading ==)

but does not say why. Is this fixable?

**Comment by Rican7** [comment]
Because the `[` and `]` characters conflict with [Markdown's link generating syntax](http://daringfireball.net/projects/markdown/syntax#link).

So, no, its not fixable without some awkward escaping rules... which MediaWiki already has provided for us with the `(== Heading ==)` tag.

**Comment by hacklschorsch** [comment]
I see. Thanks for explaining!

**Comment by Rican7** [comment]
No probem :smiley:
