### ISSUE TITLE
Is this extension maintained ?

### ISSUE THREAD

**Issue by kleag** [Rican7/MediaWiki-MarkdownExtraParser#6]
Hi,

Seeing no commit in 4 years, I wonder wether this extension is maintained or not ? Is it compatible with recent versions of WediaWiki ? Should it be activated in production ?

Thanks in advance.

Gaël

**Comment by Rican7** [comment]
No, it is not actively maintained. Sorry.

I'll be archiving this repository.

Best of luck. 🙂
